<?php
function gerarSlug($texto)
{
    $texto = trim($texto);

    // Substitui acentos manualmente
    $acentos = array(
        'á',
        'à',
        'ã',
        'â',
        'ä',
        'é',
        'è',
        'ê',
        'ë',
        'í',
        'ì',
        'î',
        'ï',
        'ó',
        'ò',
        'õ',
        'ô',
        'ö',
        'ú',
        'ù',
        'û',
        'ü',
        'ç',
        'Á',
        'À',
        'Ã',
        'Â',
        'Ä',
        'É',
        'È',
        'Ê',
        'Ë',
        'Í',
        'Ì',
        'Î',
        'Ï',
        'Ó',
        'Ò',
        'Õ',
        'Ô',
        'Ö',
        'Ú',
        'Ù',
        'Û',
        'Ü',
        'Ç'
    );
    $sem_acentos = array(
        'a',
        'a',
        'a',
        'a',
        'a',
        'e',
        'e',
        'e',
        'e',
        'i',
        'i',
        'i',
        'i',
        'o',
        'o',
        'o',
        'o',
        'o',
        'u',
        'u',
        'u',
        'u',
        'c',
        'a',
        'a',
        'a',
        'a',
        'a',
        'e',
        'e',
        'e',
        'e',
        'i',
        'i',
        'i',
        'i',
        'o',
        'o',
        'o',
        'o',
        'o',
        'u',
        'u',
        'u',
        'u',
        'c'
    );
    $texto = str_replace($acentos, $sem_acentos, $texto);

    $texto = strtolower($texto);
    $texto = preg_replace('/[^a-z0-9]/', '-', $texto);
    $texto = preg_replace('/-+/', '-', $texto);
    return trim($texto, '-');
}
